### ISSUE TITLE
Variable Naming Convention

### ISSUE THREAD

**Issue by ahuhn14** [bluemarblepayroll/sqlstyle.guide#2] opened 2020-02-13 18:54 UTC
When we are reading in variables into a proc I know we already use "_" at the beginning of the variable. Should the rest be in caps or no?

_variable 
OR 
_VARIABLE

**Comment by gerryster** [comment] 2020-03-02 21:16
Duplicate of #4 so closing.

**Closed by gerryster** 2020-03-02 21:16 UTC
Labels: duplicate
